<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_billedCharges</name>
   <tag></tag>
   <elementGuidId>b93c9b10-4012-4850-9cb8-151a55294d82</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;details&quot;]/div/div[2]/div[2]/div[3]/div[1]/div/div[1]/div/input[@name=&quot;chargeAmount&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;details&quot;]/div/div[2]/div[2]/div[3]/div[1]/div/div[1]/div/input[@name=&quot;chargeAmount&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;details&quot;]/div/div[2]/div[2]/div[3]/div[1]/div/div[1]/div/input[@name=&quot;chargeAmount&quot;]</value>
   </webElementProperties>
</WebElementEntity>
