<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_noneNetwork</name>
   <tag></tag>
   <elementGuidId>dd92571f-5a4c-4217-9d2d-3fdaa2f70d18</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;details&quot;]//div/input[@type=&quot;radio&quot;][@value=&quot;1&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;details&quot;]//div/input[@type=&quot;radio&quot;][@value=&quot;1&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;details&quot;]//div/input[@type=&quot;radio&quot;][@value=&quot;1&quot;]</value>
   </webElementProperties>
</WebElementEntity>
