<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_clientGroupId</name>
   <tag></tag>
   <elementGuidId>3121bd40-745d-4e5b-8c4c-708bce67fe0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//select[@name=&quot;clientGroupId&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name=&quot;clientGroupId&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//select[@name=&quot;clientGroupId&quot;]</value>
   </webElementProperties>
</WebElementEntity>
