<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Regression suite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>30276744-df7c-45c6-9efa-fbe6d78acd80</testSuiteGuid>
   <testCaseLink>
      <guid>f2d1bcef-ed23-4a05-9f3e-12fae11f51b5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UI/Client/Claim Services/Add_NewClaim</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>f50aeb4d-b9d2-4716-b5d9-29879be46cd1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UI/Client/Claim Services/Claim_Details</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>f5b4a3c4-f33a-440c-9419-9ca30194fa95</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UI/Client/Claim Services/Download_successful</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>d9b53871-66a4-4825-aa69-87e5980b1e8a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UI/Client/Claim Services/Search_Successful</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>3035be69-db2f-4672-b671-923cb5acd9ce</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UI/Client/Claim Services/Search_Unsuccessful</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>9a2c24f1-61ac-4eab-a5ee-4bac8d3fda90</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UI/Client/Claim Services/UploadFile_MedicalRecords</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>74d7865e-31fa-4ad4-9b3c-3860622c99ef</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UI/Client/Claim Services/UploadFile_Other</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>cd7d0772-6352-409b-911e-338ee7607f2c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UI/Client/Client Services/Account Maintenance/Account - Change password</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>825780b6-04ee-45fb-8036-d93f0142b061</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>01a18902-723c-410c-9e63-1b7aaa7a4cae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e7566d0e-595c-411f-9fb0-33a742766197</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>de702159-c116-4ef2-beaf-2c1a323c767a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5d2f93d2-b65d-4007-868c-47542f328b28</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UI/Client/Client Services/Account Maintenance/Account - Fields and buttons validation</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>4a706f14-0000-45c1-82ef-2f16b6843469</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UI/Client/Client Services/Account Maintenance/Account - Fields can be modified and saved</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>46f0c154-2d97-4cea-9b7c-b1702154e164</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b0516459-0e2a-494d-a38f-3665729243b5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a5a4efe8-248c-4d8f-84cf-9c936eaf1479</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>58e259cd-cccc-4e3d-9c46-e4789e9401ae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cbb8f072-237b-426c-9e8d-7f5428319868</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>280529bf-0552-4e2a-9e8d-3332ff2be517</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f31f2759-4c4c-47af-99f6-e6c2f8d54c93</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UI/Client/Client Services/Login/Login - Successful Client</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5bcc89e0-03ba-4a2d-adfc-5ae8ffa63d4a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>729ba0fa-b07f-4bc6-a57a-0f328e71d6ff</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>dd5f7609-bd85-421a-a6dd-274487d9d86e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UI/Client/Rule Editor/Create New Rule Set</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>9ebe8189-9674-4114-9314-b1242bbd143f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UI/Client/Rule Editor/Delete Rule Set</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>3b28342e-26d3-4913-8759-68170d50a88e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UI/Client/Rule Editor/Edit Rule Set</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>b1fff1f4-bb65-4341-b38e-d3eeaaada526</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UI/Client/Rule Editor/Search for Rule Set</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>8ef48f1e-b1ae-4a3b-959e-f39d6f980487</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UI/Client/Turn Around Tracker/Filtering</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>fb1ba2c5-9e3f-44cb-88f4-088993ee482a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UI/Client/Turn Around Tracker/General_Display</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>33e511d5-87ac-4477-aa73-baf27f605fd9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UI/Employee/Care Navigator/Care Navigator Test Cases</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2f219f4e-b77a-4431-a2a8-4be43013831e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c8147146-45a6-4e50-8f41-9008769cedd6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UI/Employee/Client Selector/Client selector - Filter works correctly</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>27efa91a-62e3-48ab-afca-bce548151b6b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UI/Employee/Client Selector/Client selector - Search and select an active client</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>827c26a2-7a99-4f81-9bf7-1256bb5356e7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>51d85246-8753-40bf-a033-2a7d8e879789</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b109b718-8ba4-4279-b0d6-a57fe38c47f5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>53974d04-da8a-4618-ba98-2d49e842db00</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UI/Employee/Client Selector/Client selector - Verify presence of elements</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>611fcb40-4857-4542-b607-b25f4d512473</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UI/Employee/Client Services/Account Maintenance/Account - Change password</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b14869d3-95fb-464b-b145-8f6f6ffeb591</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6a0c6ca7-3312-4282-8917-a7d50d6731aa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>111ec7c8-f121-459a-a6a9-59d2f736d84c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9b8a3cfa-33de-4e2d-9627-2a2eb8bb89a1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>60bb093b-130a-4761-9831-9617f0b6c3e7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UI/Employee/Client Services/Account Maintenance/Account - Fields and buttons validation</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>27110cec-0985-428d-87b7-789da9c1bbdb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UI/Employee/Client Services/Account Maintenance/Account - Fields can be modified and saved</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f9bb0fe3-2594-4ad0-88c9-a742673123d1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9a0b18be-a020-4521-bd54-2519e50c7135</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d5d7513-2776-490e-badf-79ea1921f959</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f88c6f10-e158-47e6-af21-29eb685b0a7a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aa8d5e0f-a443-41a9-a277-de2b9f90c016</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9b14d778-5bd0-4fcb-9549-e8126cca0fce</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>972467e2-dd58-450c-b571-5c62c04992b5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UI/Employee/Client Services/Forgot Password/Forgot password - Incorrect code and clicks submit</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>79d53cbf-5112-45cd-a87f-71f9e575fc11</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UI/Employee/Client Services/Forgot Password/Forgot password - No code and click submit</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>e5016ed9-5e5d-4673-99e6-1ca2ecacbfde</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UI/Employee/Client Services/Forgot Password/Forgot password - page fields validation</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b405de6e-d906-408b-a4a7-ae7409152847</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>790f90e3-da5d-4429-8f6b-d8782079ff9e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e1bd0d89-ec10-4495-b297-b4f840492fdc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UI/Employee/Client Services/Login/Login - Incorrect credentials</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>52eb9952-6036-4e53-bed4-fe284a45718f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aa574131-0e34-44a3-a721-4d67e6fdf083</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>73afe022-8c40-4b7d-be56-c85929e3b2a2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cf9ff731-bacb-46a7-8c5b-70d9e5eadc8d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bf684a23-a026-4725-85f8-c3417d51a698</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UI/Employee/Client Services/Login/Login - Successful Employee</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ef205fd0-feff-42c9-82c5-3ae51ab1eff5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>44b254b5-8054-4188-bd9f-3e89eae8ae47</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>eac6b710-8a10-4975-b734-4ca57ea63584</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UI/Employee/Files/Upload file</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>2e57cf3f-3644-4886-b008-84ab66d8feff</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UI/Employee/Files/Uploader</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>77143a8b-8fc8-4669-b712-ee8a205109ec</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UI/Employee/Performance Monitor/General Display</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>419d8ae2-1044-4c5f-bfc8-e23b985df825</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UI/Employee/Performance Monitor/Verify there is a change on the graphic</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>4f0d7ec1-2b6b-4e77-968a-281b596b3429</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UI/Employee/Report Manager/Report Types/Report Types - Create new report</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0e336a3c-8b7d-4067-a1e5-4f0e07be6e33</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7c8a7feb-bae9-448b-89b2-726d903fcf5a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UI/Employee/Report Manager/Report Types/Report Types - Delete report</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>190d5ea8-e4f3-4db0-8cfa-db82a84a5a88</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>70a07f1d-dc12-4a86-a63e-6a37ec5863d0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UI/Employee/Report Manager/Report Types/Report Types - Edit report</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8a292845-0d32-41ac-939f-1e771184d202</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>74a94bab-6d20-473c-9781-e09809fbab0f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>96a0c868-acec-4926-82ee-1a6cc55309d6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UI/Employee/Report Manager/Report Types/Report Types - Validate object presence</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>209c3851-bc05-43c0-83e8-1067b31c0bfc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UI/Employee/Report Manager/Schedule Reports/Schedule Reports - Delete Report</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b7047214-8452-44ed-8784-ad592a62e62a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c91b1b28-0587-4e39-86c2-839e1af57a6b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UI/Employee/Report Manager/Schedule Reports/Schedule Reports - Edit Schedule Report</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d9c66368-9768-493d-9f1b-40710148a0db</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9cafc7da-a6ff-4c8e-9ea7-1f3b03d25582</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UI/Employee/Report Manager/Schedule Reports/Schedule Reports - Filter by Column</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>97717cd1-1fb7-402f-b197-d0f5f98e10bc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b59ae5cd-5188-4942-b6d9-e9d1be0269fb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UI/Employee/Report Manager/Schedule Reports/Schedule Reports - Filter by Report Name</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c9ddcfc1-b5ec-44d3-9d41-326ebce94d6c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>008824a8-f049-4b39-b163-db6f808abcb0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UI/Employee/Report Manager/Schedule Reports/Schedule Reports - New schedule and search</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>05f64080-0564-46d5-92cc-21f79e5a306a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>88d885bb-5e1c-4cfb-b9d9-7ad1ad3ff30f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UI/Employee/Report Manager/Schedule Reports/Schedule Reports - Validate fields presence</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>6821640a-89f4-4ea6-b96f-b80664522819</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UI/Employee/Users Editor/Create an AMPS user</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>bcffaab1-0c2b-4093-9ba2-4d468f4f16fc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UI/Employee/Users Editor/Create not an AMPS user normal customer</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>5eb180cc-ae7a-4670-b969-30cba6bd51b6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UI/Employee/Users Editor/user can disable another user</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>f98be944-49e0-4677-acef-a2ea9dd9733b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UI/Employee/Users Editor/user can make active another user</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>4e86e662-285e-4947-b92c-392f2e1a6a58</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UI/Employee/Users Editor/User can send a Welcome Email</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>431e8fbb-49c4-4126-86d2-0503d16505af</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UI/Employee/Users Editor/User with edit role can edit admin users</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>720d1eb7-c430-40bf-862d-203b522bc029</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UI/Employee/Users Editor/User with edit role can edit users</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>ec948cdd-bdae-4d62-987c-09c789de3dcb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UI/Employee/Users Editor/User with no admin role can not edit users</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
