<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_scriptOutputTable</name>
   <tag></tag>
   <elementGuidId>38fe97c7-4df8-46fc-acf9-e2fcab39ac4a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;content&quot;]//div//div[2]/table//tr[2]//div[@class=&quot;table-head&quot;]/label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;content&quot;]//div//div[2]/table//tr[2]//div[@class=&quot;table-head&quot;]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;content&quot;]//div//div[2]/table//tr[2]//div[@class=&quot;table-head&quot;]/label</value>
   </webElementProperties>
</WebElementEntity>
