<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_expandRuleSet</name>
   <tag></tag>
   <elementGuidId>c949e513-e31a-4968-9df1-7a49a44e6528</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;content&quot;]//table/tbody/tr[1]/td[1]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;content&quot;]//table/tbody/tr[1]/td[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;content&quot;]//table/tbody/tr[1]/td[1]</value>
   </webElementProperties>
</WebElementEntity>
