<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_executedRuleTable</name>
   <tag></tag>
   <elementGuidId>e619fa32-1389-4eda-9577-f53cf37f664b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;content&quot;]//div//div[2]/table//tr[2]//div[@class=&quot;react-bs-table-container&quot;]/div[2]/div[2]/table/tbody/tr[1]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;content&quot;]//div//div[2]/table//tr[2]//div[@class=&quot;react-bs-table-container&quot;]/div[2]/div[2]/table/tbody/tr[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;content&quot;]//div//div[2]/table//tr[2]//div[@class=&quot;react-bs-table-container&quot;]/div[2]/div[2]/table/tbody/tr[1]</value>
   </webElementProperties>
</WebElementEntity>
