<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Account Maintenance - Client</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>12517608-a11b-47b3-9d20-8813a6c660d4</testSuiteGuid>
   <testCaseLink>
      <guid>09f73214-8bac-4924-91db-e614d72f878f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UI/General/openBrowser</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>898c79fb-320c-4071-a93d-1d2fc316f153</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UI/General/Client Login</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cf2ffeda-d199-4d97-ae57-1f68d1c49452</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0cee8dca-bc3b-4a56-814c-982fe5ae0c77</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>af7456e7-c93c-44f7-bee5-d50b25f17af1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UI/Client/Client Services/Account Maintenance/Account - Fields and buttons validation</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>cc1e4183-637d-4e50-96e5-5a19db0dc25d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UI/Client/Client Services/Account Maintenance/Account - Fields can be modified and saved</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c2b8faad-82e4-4a4f-82d6-e44403902fc1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3ef265e3-f2b2-4f33-9595-765ce0ad807f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d288e4a2-d926-4a4e-8a47-14369aaa56e0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0fae7e96-4a69-40bd-bd38-2cbba0f38095</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>50bfee53-60d1-473c-a4b9-c029e1cdb9c1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9f351cba-e433-4fca-ab46-baf5ed3aff9f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>425f0c4a-5d51-458e-8cb1-3a51cff30a6b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UI/Client/Client Services/Account Maintenance/Account - Change password</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>db2db444-09a0-489f-967c-96fa2d84dabc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>546de3d7-404a-4dca-bd6b-95278fcebe41</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fbdf901f-3062-43e5-bc9b-388ee8c6847b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>833d21a4-7b21-4b93-84a8-f5874ffc609e</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
