<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Account Maintenance - Employee</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>f124bce7-a2e2-4c12-b958-943ce10fb03d</testSuiteGuid>
   <testCaseLink>
      <guid>02c55365-8d77-4017-b517-84889a509654</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UI/General/openBrowser</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>12a26dbd-4a04-4938-a9ad-11f7fd5d4b9e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UI/General/Employee Login</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1ddd7686-eeb7-4a6b-92b7-f7108b4020ca</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>22d00e95-c79c-43a1-9f4a-be35e0bf2504</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>70fbf5b8-7243-4645-a4f2-155b908157ee</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UI/Employee/Client Services/Account Maintenance/Account - Fields and buttons validation</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>1505acff-2011-4a80-8234-25ce510bd918</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UI/Employee/Client Services/Account Maintenance/Account - Fields can be modified and saved</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f9bb0fe3-2594-4ad0-88c9-a742673123d1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9a0b18be-a020-4521-bd54-2519e50c7135</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d5d7513-2776-490e-badf-79ea1921f959</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f88c6f10-e158-47e6-af21-29eb685b0a7a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aa8d5e0f-a443-41a9-a277-de2b9f90c016</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9b14d778-5bd0-4fcb-9549-e8126cca0fce</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3239290e-d1a4-491b-b8bd-90dd566303a7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UI/Employee/Client Services/Account Maintenance/Account - Change password</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b14869d3-95fb-464b-b145-8f6f6ffeb591</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6a0c6ca7-3312-4282-8917-a7d50d6731aa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>111ec7c8-f121-459a-a6a9-59d2f736d84c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9b8a3cfa-33de-4e2d-9627-2a2eb8bb89a1</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
