<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Account Maintenance - Employee</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>f124bce7-a2e2-4c12-b958-943ce10fb03d</testSuiteGuid>
   <testCaseLink>
      <guid>02c55365-8d77-4017-b517-84889a509654</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UI/General/openBrowser</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>12a26dbd-4a04-4938-a9ad-11f7fd5d4b9e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UI/General/Employee Login</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1ddd7686-eeb7-4a6b-92b7-f7108b4020ca</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>22d00e95-c79c-43a1-9f4a-be35e0bf2504</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1505acff-2011-4a80-8234-25ce510bd918</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UI/Employee/Client Services/Account Maintenance/Account - Fields can be modified and saved</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>edaab091-cf2e-4394-8a2b-081db5b8e16d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4c3a8e24-36ea-4941-bde1-3c31f71da11e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b0b90f6b-d15b-4dd2-9581-dd71c12784df</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dcab0bed-a2ad-40c0-a9a8-cbddacc9eb11</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>52b380c5-5eca-4e45-b2bd-333bacb85b5e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8672b346-0a33-47f9-a0f3-4d82e325a011</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>70fbf5b8-7243-4645-a4f2-155b908157ee</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UI/Employee/Client Services/Account Maintenance/Account - Fields and buttons validation</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>3239290e-d1a4-491b-b8bd-90dd566303a7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UI/Employee/Client Services/Account Maintenance/Account - Change password</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9dce466d-920f-4232-9980-a775ccc9d881</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>68daeff0-9013-44c5-a5d8-3be7355a1388</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>db7839f9-360b-4b1e-a941-62648f230f54</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b08eef27-9977-4da3-8f76-f670d7ba8bc2</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
