<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Login - Employee</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>10786e1a-8713-4564-bb39-ab7c3cf69b99</testSuiteGuid>
   <testCaseLink>
      <guid>9d1013b9-ab66-4e9f-b48a-02e7d98c5661</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UI/Employee/Client Services/Login/Login - Successful Employee</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>65ae76ee-4cfd-4982-ad1b-124831124ad5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7481918a-a651-4573-b9ec-911a4c7c56c9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ed58feb9-7c23-4926-8200-43f3b7bd4a28</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UI/General/openBrowser</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>b61e0094-dbb1-40d3-bcd9-69eee03280e1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UI/Employee/Client Services/Login/Login - Incorrect credentials</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f6fd0526-011c-4f32-a5b0-7977c974d0f3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>45ef49dc-94e6-4474-a599-f616e3078c95</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ddcb31ec-25c6-42cb-b389-744149e8c194</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3da6ea5a-0d12-4fe3-bf1f-b2e468c39ec7</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
