<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_editRuleSetIcon</name>
   <tag></tag>
   <elementGuidId>dd8b4b35-624c-478c-b130-ec4681d97887</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;content&quot;]//table/tbody/tr[1]/td[8]/div/a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;content&quot;]//table/tbody/tr[1]/td[8]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;content&quot;]//table/tbody/tr[1]/td[8]/div/a</value>
   </webElementProperties>
</WebElementEntity>
