<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_firstExistingFile</name>
   <tag></tag>
   <elementGuidId>2ddc75ef-f03a-45db-9f0d-e42018e47a06</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;files&quot;]//table/tbody/tr[1]/td[2]/a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;files&quot;]//table/tbody/tr[1]/td[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;files&quot;]//table/tbody/tr[1]/td[2]/a</value>
   </webElementProperties>
</WebElementEntity>
