<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_clientsHeader</name>
   <tag></tag>
   <elementGuidId>4d4c47b1-0ddd-4dbf-841f-6cb3fcd16c83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@class=&quot;header-title&quot;]/h1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class=&quot;header-title&quot;]/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class=&quot;header-title&quot;]/h1</value>
   </webElementProperties>
</WebElementEntity>
