<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_turnAroundTrackerHeader</name>
   <tag></tag>
   <elementGuidId>b42ce774-2e4f-4e05-ba7e-1914120ffe50</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@class=&quot;header-title&quot;]/h1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class=&quot;header-title&quot;]/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class=&quot;header-title&quot;]/h1</value>
   </webElementProperties>
</WebElementEntity>
