<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ruleSetName</name>
   <tag></tag>
   <elementGuidId>04303377-9ae9-4ae3-b69f-a51d53a12f42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class=&quot;page-body&quot;]//input[@name=&quot;name&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class=&quot;page-body&quot;]//input[@name=&quot;name&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class=&quot;page-body&quot;]//input[@name=&quot;name&quot;]</value>
   </webElementProperties>
</WebElementEntity>
