<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_validToDate</name>
   <tag></tag>
   <elementGuidId>7c8dae22-cbd8-42ac-96c3-8278e7a3d2f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;content&quot;]/div/div/div/div[3]/div[2]/div/div/div/form/div/div/div/div/div[2]/div/div[3]/div/div[1]/span[1]/input[1]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;content&quot;]/div/div/div/div[3]/div[2]/div/div/div/form/div/div/div/div/div[2]/div/div[3]/div/div[1]/span[1]/input[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;content&quot;]/div/div/div/div[3]/div[2]/div/div/div/form/div/div/div/div/div[2]/div/div[3]/div/div[1]/span[1]/input[1]</value>
   </webElementProperties>
</WebElementEntity>
