<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>option_claimType</name>
   <tag></tag>
   <elementGuidId>5eac56c6-5bc4-45a3-9d02-6e9f6562e443</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class=&quot;Select-control&quot;]//div[@class=&quot;Select-input&quot;]/input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class=&quot;Select-control&quot;]//div[@class=&quot;Select-input&quot;]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class=&quot;Select-control&quot;]//div[@class=&quot;Select-input&quot;]/input</value>
   </webElementProperties>
</WebElementEntity>
