<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_addCondition</name>
   <tag></tag>
   <elementGuidId>9cb588bf-fa49-4cb6-bdbf-dc0d154f5193</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;react-select-5--value&quot;)/div[@class=&quot;Select-input&quot;]/input[1]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>id(&quot;react-select-5--value&quot;)/div[@class=&quot;Select-input&quot;]/input[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-5--value&quot;)/div[@class=&quot;Select-input&quot;]/input[1]</value>
   </webElementProperties>
</WebElementEntity>
