<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Element Dropdown Files Users</name>
   <tag></tag>
   <elementGuidId>b008f7e2-d99a-469a-8c9a-bcb3304faa83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div/div/div/div/div[3]/div[2]/div/div[2]/div/div[2]/div/form/div[1]/div/div/div[1]/div/div[1]/div/div/span[1]/div[2]/input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div[3]/div[2]/div/div[2]/div/div[2]/div/form/div[1]/div/div/div[1]/div/div[1]/div/div/span[1]/div[2]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div/div/div/div/div[3]/div[2]/div/div[2]/div/div[2]/div/form/div[1]/div/div/div[1]/div/div[1]/div/div/span[1]/div[2]/input</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <value>/html/body/div/div/div/div/div[3]/div[2]/div/div[2]/div/div[2]/div/form/div[1]/div/div/div[1]/div/div[1]/div/div/span[1]/div[2]/input</value>
   </webElementXpaths>
</WebElementEntity>
